coverage:
    paths:
        - /home/qrf/workarea/gillian/ria/ria/utils/utils/tests/utils/helpers
    status:
        project:
            default:
                target: 60%
                threshold: 5%
                if_ci_failed: error