contact_links:
  - name: Support
    url: https://github.com/qoherent/ria/discussions/categories/support
    about: "If you have any questions or need assistance, please don't hesitate to reach out on our open support forum."
