name: "Docs Build Successfully on PR Check"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - uses: ammaraskar/sphinx-action@0.4
         with:
          docs-folder: "docs/"
          pre-build-command: pip install -U sphinx sphinx-rtd-theme
       - uses: actions/upload-artifact@v4
         with:
          name: UserGuideHTML
          path: "docs/build/html/"