name: "Docs Build Successfully on PR Check"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out 
        uses: actions/checkout@v3
    
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -U sphinx sphinx-rtd-theme

      - name: Annotate PR with Sphinx Docs Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs"