name: flake8 Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Flake8 Lint
    steps:
        - name: Check out 
          uses: actions/checkout@v4

        - name: Set up Python environment
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry lock --no-update
            poetry install
            pip install black
            pip install isort

        - name: Run Black
          run: black ./ --config pyproject.toml

        - name: Check Black formatting
          uses: psf/black@stable
          with:
            options: "--check --verbose"
            src: "./"
            use_pyproject: true
            version: "~= 24.4"

        - name: Run Isort
          run: isort .

        - name: Check Isort formatting
          uses: isort/isort-action@master

        - name: Setup flake8 annotations
          uses: rbialon/flake8-annotations@v1.1

        - name: Link and annotate with Flake8
          uses: py-actions/flake8@v2