name: Build-sphinx-docs

on:
  push:
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
           python-version: "3.10"
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -U sphinx sphinx-rtd-theme ghp-import
      - name: Build HTML
        run: | 
          cd docs/
          make clean
          make html
      - name: Run ghp-import
        run: | 
          ghp-import -n -c radiointelligence.io -p -f docs/build/html